"""Curated list of companies that historically sponsor H1B at $140k+ TC.

Each entry: (slug, ats). The fetcher hits the ATS's public board API for that slug.
Slugs are best-effort — the script logs and skips 404s, so over-inclusion is fine.

To add: append a tuple. To remove: delete the line.
"""

COMPANIES: list[tuple[str, str]] = [
    # ---- Greenhouse ----
    ("airbnb", "greenhouse"),
    ("doordash", "greenhouse"),
    ("instacart", "greenhouse"),
    ("lyft", "greenhouse"),
    ("dropbox", "greenhouse"),
    ("pinterest", "greenhouse"),
    ("reddit", "greenhouse"),
    ("redditinc", "greenhouse"),
    ("gitlab", "greenhouse"),
    ("twitch", "greenhouse"),
    ("coinbase", "greenhouse"),
    ("plaid", "greenhouse"),
    ("robinhood", "greenhouse"),
    ("chime", "greenhouse"),
    ("brex", "greenhouse"),
    ("ramp", "greenhouse"),
    ("mercury", "greenhouse"),
    ("affirm", "greenhouse"),
    ("sofi", "greenhouse"),
    ("stripe", "greenhouse"),
    ("cloudflare", "greenhouse"),
    ("datadog", "greenhouse"),
    ("mongodb", "greenhouse"),
    ("snowflake", "greenhouse"),
    ("databricks", "greenhouse"),
    ("confluent", "greenhouse"),
    ("elastic", "greenhouse"),
    ("notion", "greenhouse"),
    ("figma", "greenhouse"),
    ("discord", "greenhouse"),
    ("scaleai", "greenhouse"),
    ("gong", "greenhouse"),
    ("glean", "greenhouse"),
    ("samsara", "greenhouse"),
    ("benchling", "greenhouse"),
    ("hashicorp", "greenhouse"),
    ("asana", "greenhouse"),
    ("lattice", "greenhouse"),
    ("gusto", "greenhouse"),
    ("postman", "greenhouse"),
    ("retool", "greenhouse"),
    ("webflow", "greenhouse"),
    ("vercel", "greenhouse"),
    ("contentful", "greenhouse"),
    ("carta", "greenhouse"),
    ("sigmacomputing", "greenhouse"),
    ("snyk", "greenhouse"),
    ("wiz", "greenhouse"),
    ("tailscale", "greenhouse"),
    ("fivetran", "greenhouse"),
    ("dbtlabs", "greenhouse"),
    ("montecarlodata", "greenhouse"),
    ("grafanalabs", "greenhouse"),
    ("zendesk", "greenhouse"),
    ("twilio", "greenhouse"),
    ("intercom", "greenhouse"),
    ("hubspot", "greenhouse"),
    ("squarespace", "greenhouse"),
    ("squareup", "greenhouse"),
    ("blockinc", "greenhouse"),
    ("toast", "greenhouse"),
    ("klaviyo", "greenhouse"),
    ("attentive", "greenhouse"),
    ("clickup", "greenhouse"),
    ("airtable", "greenhouse"),
    ("miro", "greenhouse"),
    ("zoom", "greenhouse"),
    ("zscaler", "greenhouse"),
    ("crowdstrike", "greenhouse"),
    ("cribl", "greenhouse"),
    ("sumologic", "greenhouse"),
    ("dropboxinc", "greenhouse"),
    ("boxinc", "greenhouse"),
    ("oktainc", "greenhouse"),
    ("rippling", "greenhouse"),
    ("deelinc", "greenhouse"),
    ("auth0", "greenhouse"),
    ("hingehealth", "greenhouse"),
    ("anduril", "greenhouse"),
    ("clipboard", "greenhouse"),

    # ---- Lever ----
    ("netflix", "lever"),
    ("openai", "lever"),
    ("mixpanel", "lever"),
    ("kraken", "lever"),
    ("eventbrite", "lever"),
    ("attentive", "lever"),
    ("cohere", "lever"),
    ("character", "lever"),

    # ---- Ashby ----
    ("linear", "ashby"),
    ("posthog", "ashby"),
    ("replicate", "ashby"),
    ("anthropic", "ashby"),
    ("perplexity", "ashby"),
    ("ramp", "ashby"),
    ("vercel", "ashby"),
    ("modal", "ashby"),
    ("mistral", "ashby"),
    ("runwayml", "ashby"),
    ("cursor", "ashby"),
    ("warp", "ashby"),
    ("zed", "ashby"),
    ("supabase", "ashby"),
    ("railway", "ashby"),
    ("baseten", "ashby"),
    ("together", "ashby"),
    ("fireworksai", "ashby"),
    ("groq", "ashby"),
    ("crusoe", "ashby"),
    ("scale", "ashby"),
    ("gleananswers", "ashby"),
    ("writer", "ashby"),
    ("rampnetwork", "ashby"),

    # ---- Workday (slug = "tenant/site"; adapter probes wd1/wd2/wd3/wd5)
    # NOTE: Microsoft uses a custom backend (jobs.careers.microsoft.com), NOT Workday.
    ("salesforce/External_Career_Site", "workday"),
    ("nvidia/NVIDIAExternalCareerSite", "workday"),
    ("adobe/external_experienced", "workday"),
    ("intuit/External", "workday"),
    ("capitalone/Capital_One", "workday"),
    ("tmobile/External", "workday"),
    ("autodesk/Ext", "workday"),
    ("servicenow/ServiceNow", "workday"),
    ("workday/Workday", "workday"),
    ("cisco/External_Career_Site", "workday"),
    ("walmart/WalmartExternal", "workday"),
    ("paypal/jobs", "workday"),
    ("hp/ExternalCareerSite", "workday"),
    ("hpe/Jobsathpe", "workday"),
    ("vmware/VMware", "workday"),
    ("oracle/Oracle", "workday"),
    ("uber/UberCareers", "workday"),
    ("ge/GE_External_Career_Site", "workday"),
    ("att/External", "workday"),
    ("verizon/External", "workday"),
    ("comcast/Comcast_Careers", "workday"),
    ("citi/2", "workday"),
    ("jpmc/External_search", "workday"),
    ("bmo/External", "workday"),
    ("ibm/External_Career", "workday"),
    ("dell/External_Career_Site", "workday"),
    ("amd/External_Career_Site", "workday"),
    ("micron/External", "workday"),
    ("appliedmaterials/External", "workday"),

    # ---- SmartRecruiters ----
    ("Visa", "smartrecruiters"),
    ("Bosch", "smartrecruiters"),
    ("Square", "smartrecruiters"),
    ("PublicisGroupe", "smartrecruiters"),
    ("McAfee", "smartrecruiters"),

    # ---- Workable (smaller startups; over-inclusion is fine — slug 404s skip) ----
    ("pleo", "workable"),
    ("checkly", "workable"),
    ("nccgroupplc", "workable"),
]


def by_ats() -> dict[str, list[str]]:
    """Group company slugs by ATS."""
    grouped: dict[str, list[str]] = {}
    for slug, ats in COMPANIES:
        grouped.setdefault(ats, []).append(slug)
    # de-dup within each ATS
    return {k: sorted(set(v)) for k, v in grouped.items()}
